ARG BASE_IMAGE=registry.fly.io/wayne-w4y:fly240
FROM ${BASE_IMAGE}
COPY work4you_cli/dashboard_auth/platform_sso.py /opt/wayne/wayne_cli/dashboard_auth/platform_sso.py
COPY work4you_cli/dashboard_auth/cookies.py /opt/wayne/wayne_cli/dashboard_auth/cookies.py
COPY work4you_cli/relay_free_model.py /opt/wayne/wayne_cli/relay_free_model.py