# SPA-only overlay - refresh app_dist on existing tenant image
ARG BASE_IMAGE=registry.fly.io/wayne-w4y:fly242
FROM ${BASE_IMAGE}

RUN rm -rf \
    /opt/work4you/work4you_cli/app_dist /opt/wayne/wayne_cli/app_dist

COPY work4you_cli/app_dist /opt/work4you/work4you_cli/app_dist
COPY work4you_cli/app_dist /opt/wayne/wayne_cli/app_dist

RUN ln -sfn app_dist /opt/wayne/wayne_cli/web_dist && \
    ln -sfn app_dist /opt/work4you/work4you_cli/web_dist